import { Header } from '@/components/common';
import { Hero, Partner, Service } from '@/components/features';
import { getSettings } from '@/utils';
import Head from 'next/head';

interface HomeProps {
  hero: any;
  partner: any;
  service: any;
}

const Home = ({ hero, partner, service }: HomeProps) => {
  return (
    <>
      <Head>
        <title>Dision GmbH & Co.KG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero {...hero} />
      <Partner {...partner} />
      <hr />
      <Service {...service} />
      {/* <Footer /> */}
    </>
  );
};

export default Home;

export async function getStaticProps() {
  const { hero, partner, service } = getSettings();

  return {
    props: { hero, partner, service },
    revalidate: 60,
  };
}
