import { Header } from '@/components/common';
import { About, Hero, Partner, Refer, Service, Stats } from '@/components/features';
import { getSettings } from '@/utils';
import Head from 'next/head';

interface HomeProps {
  hero: any;
  partner: any;
  service: any;
  about: any;
  stats: any;
}

const Home = ({ hero, partner, service, about, stats }: HomeProps) => {
  return (
    <>
      <Head>
        <title>Dision GmbH & Co.KG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero {...hero} />
      <Partner {...partner} />
      <hr />
      <Service {...service} />
      <About {...about} />
      <Stats {...stats} />
      <Refer />
      {/* <Footer /> */}
    </>
  );
};

export default Home;

export async function getStaticProps() {
  const { hero, partner, service, about, stats } = getSettings();

  return {
    props: { hero, partner, service, about, stats },
    revalidate: 60,
  };
}
