import { Footer, Header } from '@/components/common';
import { About, Hero, Partner, Refer, Service, Stats } from '@/components/features';
import { getSettings } from '@/utils';
import Head from 'next/head';

interface HomeProps {
  header: any;
  hero: any;
  partner: any;
  service: any;
  about: any;
  stats: any;
  refer: any;
  footer: any;
}

const Home = ({ header, hero, partner, service, about, stats, refer, footer }: HomeProps) => {
  return (
    <>
      <Head>
        <title>Professional Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header {...header} />
      <Hero {...hero} />
      <Partner {...partner} />
      <hr />
      <Service {...service} />
      <About {...about} />
      <Stats {...stats} />
      <Refer {...refer} />
      <Footer {...footer} />
    </>
  );
};

export default Home;

export async function getStaticProps() {
  const { header, hero, partner, service, about, stats, refer, footer } = getSettings();

  return {
    props: { header, hero, partner, service, about, stats, refer, footer },
    revalidate: 60,
  };
}
